services:
  backend:
    build: ./backend
    container_name: elysion_backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    env_file:
      - ./backend/.env
    networks:
      - elysion_network

  database:
    image: mysql:latest
    container_name: elysion_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - elysion_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: elysion_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
    networks:
      - elysion_network


networks:
  elysion_network:
    driver: bridge

volumes:
  db_data:
